application: to-get
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /vendor
  static_dir: bower_components

- url: /static
  static_dir: static

- url: /api/.*
  script: api.application

- url: /cron/.*
  script: cron.application
  login: admin

- url: /.*
  static_files: static/app.html
  upload: static/app.html
